<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yoLLRfE' shared service.

return $this->privates['.service_locator.yoLLRfE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'flight' => ['privates', '.errored..service_locator.yoLLRfE.App\\Entity\\Flight', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Flight" but no such service exists.'],
], [
    'flight' => 'App\\Entity\\Flight',
]);
