<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TIQ6ltY' shared service.

return $this->privates['.service_locator.TIQ6ltY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FlightController::delete' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\FlightController::edit' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\FlightController::index' => ['privates', '.service_locator.RfM5EXj', 'get_ServiceLocator_RfM5EXjService.php', true],
    'App\\Controller\\FlightController::show' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\PostController::delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController::show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\FlightController:delete' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\FlightController:edit' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\FlightController:index' => ['privates', '.service_locator.RfM5EXj', 'get_ServiceLocator_RfM5EXjService.php', true],
    'App\\Controller\\FlightController:show' => ['privates', '.service_locator.yoLLRfE', 'get_ServiceLocator_YoLLRfEService.php', true],
    'App\\Controller\\PostController:delete' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:edit' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController:show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
], [
    'App\\Controller\\FlightController::delete' => '?',
    'App\\Controller\\FlightController::edit' => '?',
    'App\\Controller\\FlightController::index' => '?',
    'App\\Controller\\FlightController::show' => '?',
    'App\\Controller\\PostController::delete' => '?',
    'App\\Controller\\PostController::edit' => '?',
    'App\\Controller\\PostController::index' => '?',
    'App\\Controller\\PostController::show' => '?',
    'App\\Controller\\FlightController:delete' => '?',
    'App\\Controller\\FlightController:edit' => '?',
    'App\\Controller\\FlightController:index' => '?',
    'App\\Controller\\FlightController:show' => '?',
    'App\\Controller\\PostController:delete' => '?',
    'App\\Controller\\PostController:edit' => '?',
    'App\\Controller\\PostController:index' => '?',
    'App\\Controller\\PostController:show' => '?',
]);
