<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3J7fLxu\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3J7fLxu/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container3J7fLxu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container3J7fLxu\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container3J7fLxu\srcApp_KernelProdContainer([
    'container.build_hash' => '3J7fLxu',
    'container.build_id' => '01b88376',
    'container.build_time' => 1560433765,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3J7fLxu');
