<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'flight_index' => [[], ['_controller' => 'App\\Controller\\FlightController::index'], [], [['text', '/flight/']], [], []],
    'flight_new' => [[], ['_controller' => 'App\\Controller\\FlightController::new'], [], [['text', '/flight/new']], [], []],
    'flight_show' => [['id'], ['_controller' => 'App\\Controller\\FlightController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/flight']], [], []],
    'flight_edit' => [['id'], ['_controller' => 'App\\Controller\\FlightController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/flight']], [], []],
    'flight_delete' => [['id'], ['_controller' => 'App\\Controller\\FlightController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/flight']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'secret' => [[], ['_controller' => 'App\\Controller\\SecretController::index'], [], [['text', '/secret']], [], []],
];
