<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgLQUR2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgLQUR2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYgLQUR2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYgLQUR2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYgLQUR2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YgLQUR2',
    'container.build_id' => '9c03c517',
    'container.build_time' => 1561553602,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgLQUR2');
