<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvdKBYW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvdKBYW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUvdKBYW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUvdKBYW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUvdKBYW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UvdKBYW',
    'container.build_id' => 'd25def07',
    'container.build_time' => 1561812092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvdKBYW');
